### ISSUE TITLE
Unrecoverable error: `.../config does not look like a Borg cache`

### ISSUE THREAD

**Issue by xeyownt** [xeyownt/borgcronic#23]
This is on borg 1.1.0b5.

I get an unrecoverable error on `borg create`, namely `.../config does not look like a Borg cache`.
Looking into borgcronic log file, we have (Lines with `# ` are produced by the cron job, lines without are produced by Borg itself):

```
# vendredi 1 septembre 2017, 12:55:07 (UTC+0200): [WAKEUP] Sending wakeup signal to daemon.
# vendredi 1 septembre 2017, 12:55:07 (UTC+0200): [DAEMON] Waiting for wake-up signal...
####################################################################################################
# vendredi 1 septembre 2017, 12:55:07 (UTC+0200): Starting borgcronic[16805]
# vendredi 1 septembre 2017, 12:55:08 (UTC+0200): Starting 'borg create'
# vendredi 1 septembre 2017, 12:55:08 (UTC+0200): Doing 'borg create'
# vendredi 1 septembre 2017, 12:55:08 (UTC+0200): ## borg create -v --stats -x --compression lz4 ::{hostname}_{now:%Y%m%d_%H%M} /home --exclude root/.cache --exclude *.nobak --exclude */xapiandb --exclude */.thumbnails
## Borg repo: 296935M (311359488000)
## Borg cache: 1215M (1274908672)
====================================================================================================
Synchronizing chunks cache...
Archives: 51, w/ cached Idx: 51, w/ outdated Idx: 2, w/o cached Idx: 2.
Reading cached archive chunk index for computer_20170830_2357 ...
Merging into master chunks index ...
Reading cached archive chunk index for another_computer_20170828_2317 ...
Merging into master chunks index ...
[...]
Reading cached archive chunk index for computer_20170630_0151 ...
Merging into master chunks index ...
Done.
# vendredi 1 septembre 2017, 12:54:53 (UTC+0200): [DAEMON] Waiting for wake-up signal...
# vendredi 1 septembre 2017, 17:26:59 (UTC+0200): [WAKEUP] Sending wakeup signal to daemon.
####################################################################################################
# vendredi 1 septembre 2017, 17:26:59 (UTC+0200): [DAEMON] Waiting for wake-up signal...
# vendredi 1 septembre 2017, 17:26:59 (UTC+0200): Starting borgcronic[4788]
# vendredi 1 septembre 2017, 17:26:59 (UTC+0200): Starting 'borg create'
# vendredi 1 septembre 2017, 17:26:59 (UTC+0200): Doing 'borg create'
# vendredi 1 septembre 2017, 17:26:59 (UTC+0200): ## borg create -v --stats -x --compression lz4 ::{hostname}_{now:%Y%m%d_%H%M} /home --exclude root/.cache --exclude *.nobak --exclude */xapiandb --exclude */.thumbnails
## Borg repo: 297021M (311449477120)
## Borg cache: 1197M (1255690240)
====================================================================================================
Killed stale lock computer@128437435502637.17074-0.
Removed stale exclusive roster lock for pid 17074.
Removed stale exclusive roster lock for pid 17074.
Killed stale lock computer@128437435502637.17074-0.
Removed stale exclusive roster lock for pid 17074.
Removed stale exclusive roster lock for pid 17074.
Local Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 3482, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 3410, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 122, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 469, in do_create
    lock_wait=self.lock_wait) as cache:
  File "/usr/local/lib/python3.5/dist-packages/borg/cache.py", line 195, in __init__
    self.open(lock_wait=lock_wait)
  File "/usr/local/lib/python3.5/dist-packages/borg/cache.py", line 296, in open
    self.rollback()
  File "/usr/local/lib/python3.5/dist-packages/borg/cache.py", line 388, in rollback
    self._do_open()
  File "/usr/local/lib/python3.5/dist-packages/borg/cache.py", line 283, in _do_open
    self._check_upgrade(config_path)
  File "/usr/local/lib/python3.5/dist-packages/borg/cache.py", line 264, in _check_upgrade
    raise Exception('%s does not look like a Borg cache.' % config_path) from None
Exception: /var/cache/borg/5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03/config does not look like a Borg cache.

Platform: Linux computer 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.1.0b5  Python: CPython 3.5.2
PID: 4854  CWD: /
sys.argv: ['/usr/local/bin/borg', 'create', '-v', '--stats', '-x', '--compression', 'lz4', '::{hostname}_{now:%Y%m%d_%H%M}', '/home', '--exclude', 'root/.cache', '--exclude', '*.nobak', '--exclude', '*/xapiandb', '--exclude', '*/.thumbnails']
SSH_ORIGINAL_COMMAND: None

====================================================================================================
```

Environment variables:
```
[D] # Borg variables:
[D]     BORG_KEYS_DIR=/var/lib/borg/keys
[D]     BORG_CACHE_DIR=/var/cache/borg
[D]     BORG_REPO=/smb/lacie-cloudbox/borg
[D]     BORG_SECURITY_DIR=/var/lib/borg/security
```

The repository is stored on a **samba share**.

We see two executions of `borg create`, one at 12:55:08, and a second at 17:26:59. The first got interrupted after syncing with the remote, and we see that actually the **time on the client went backwards** after the interruption (see timestamp `vendredi 1 septembre 2017, 12:54:53` after `Done.` message). In fact, looking into `kern.log`, we see that the computer was rebooted at `12:54:41`. In `auth.log`, we can see timestamps up to `12:55:01` before they get reset at `12:54:41`. The cause of this backward move is unknown.

At the second `borg create`, we see that Borg cleans up some stale lock, but then fail permanently. 
In future executions, we get always the same error (`/config does not look like a Borg cache`).

Content of `/var/cache/borg`:

```
drwx------  3 root root 4096 sep 23 16:16 ./
drwxr-xr-x 25 root root 4096 mai 22 20:12 ../
-rw-r--r--  1 root root    0 sep 23 12:47 borgcronic.success.create
-rw-r--r--  1 root root    0 sep 23 12:48 borgcronic.success.prune
-rw-r--r--  1 root root   29 sep 23 16:16 borgcronic-ts-create
-rw-r--r--  1 root root   29 sep 23 16:08 borgcronic-ts-create.fail
-rw-------  1 root root  194 mai 22 20:12 CACHEDIR.TAG
drwx------  3 root root 4096 sep 23 16:24 5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03/
```

Content of `/var/cache/borg/5891...`:
```
drwx------ 3 root root 4096 sep 23 16:24 ./
drwx------ 3 root root 4096 sep 23 16:16 ../
-rw------- 1 root root    0 sep  1 17:27 chunks
drwx------ 2 root root 4096 sep  1 12:55 chunks.archive.d/
-rw------- 1 root root    0 sep  1 17:27 config
-rw------- 1 root root    0 sep  1 17:27 files
-rw------- 1 root root   68 mai 22 20:12 README
```
We see that all files in this folder are **empty**. Looking further though, in `chunks.archive.d`, the files there seem ok.

**Comment by xeyownt** [comment]
This is same issue as in https://github.com/borgbackup/borg/issues/1501 it seems.

**Comment by xeyownt** [comment]
Doing `borg delete --cache-only /repository` does not help (with or without setting env. var. `BORG_REPO` accordingly). But `sudo rm -rf $BORG_REPO` did the trick.

**Comment by xeyownt** [comment]
The question remains how can we detect these permanent errors? In any case, the most bullet-proof solution would be to warn (by mail) in case backup fails for too long time (or after too many retries).
